kubernetes-debug
otus-kuber-2020-07/dexoid_platform pull request #12
Opened 2020-11-07 11:53 UTC by dexoid

# Выполнено ДЗ

 - [X] Основное ДЗ
 - [X] Задание со *

## В процессе сделано:
1. Работа с kubernetes-debug
 * Установил сразу рабочую версию ```debug version 0.2.0-rc``` которая прописывает нужные capabilities
 * Использовал официальную документацию, запускал так: ```kubectl debug --agentless=false POD_NAME``` предварительно установив агента для версии 1.17 (есть изменения в описании Daemonset)
 * Запускал strace без всяких проблем на nginx воркерах: ```strace -fp PID```
2. Работа с iptables-tailer
 * Установил тестовое приложение netperf-operator
 * Замерил скорость, убедился, что всё ОК
 * Применил предлагаемую политику, ествественно всё сломалось :)
 * Прошёл боль с iptables-tailer с использованем дефолтового манифеста
 * Применил манифест из снипетов, отредактировав его для совместимости с кубером 1.17 (есть изменения в описании Daemonset)
 * Создал сервис аккаунт, и биндинги, чтобы тейлер мог патчить евенты
 * Начали прилетать евенты
 * Исправил политику, чтобы разрешить трафик, снова замерил скорость, убедился, что работает
 * Почему-то перестали писать логи тейлера о блокировках, не могу разобраться :(((, с евентами всё ОК
 * Поправил параметры ENV переменных для Daemonset iptable-tailer чтобы показывает имя пода, но логи не пишутся, не получается проверить...

## Как запустить проект:
 - Применять манифесты

## PR checklist
 - [X] Выставлен label с темой домашнего задания

2020-11-11 18:21 UTC, Jasstkn requested changes
Добрый вечер. По идее вам необходимо использовать переменную со значением, которое я указала в комментарии. Тем более у вас переменная дублируется несколько раз. 
> POD_IDENTIFIER: (string, default: namespace) How to identify pods in the logs. name, label, namespace or name_with_namespace are currently supported. If label, uses the value of the label key specified by POD_IDENTIFIER_LABEL.

2020-11-11 18:21 UTC, Jasstkn commented on kubernetes-debug/kit/iptables-tailer.yaml
> +                value: "netperf-type"
вам по идее вместо этих параметров нужно использовать просто POD_IDENTIFIER = name. Попробуйте с ним проверить

2020-11-11 19:51 UTC, dexoid commented on kubernetes-debug/kit/iptables-tailer.yaml
> +                value: "netperf-type"
Если я правильно понимаю, то я убираю
`              - name: "POD_IDENTIFIER_LABEL"
                value: "netperf-type"`
и изменяю 
`              - name: "POD_IDENTIFIER"
                value: "label"`
на
`              - name: "POD_IDENTIFIER"
                value: "name"`
?

2020-11-11 20:16 UTC, Jasstkn commented on kubernetes-debug/kit/iptables-tailer.yaml
> +                value: "netperf-type"
да)

2020-11-17 16:54 UTC, dexoid commented
По-прежнему ничего не вижу в логах :(
```➜  kubernetes-debug git:(kubernetes-debug) ✗ kubectl logs --selector=app=kube-iptables-tailer -n kube-system
2020/11/17 16:40:24 Invalid value for METRICS_SERVER_PORT: using default: 9090
E1117 16:44:50.198290       1 locator.go:180] Unable to resolve address: ip=10.0.2.6, error=lookup 6.2.0.10.in-addr.arpa. on 10.4.0.10:53: no such host
2020/11/17 16:40:24 Invalid value for METRICS_SERVER_PORT: using default: 9090
2020/11/17 16:40:24 Invalid value for METRICS_SERVER_PORT: using default: 9090```

2020-11-17 18:02 UTC, dexoid commented
`  Warning  PacketDrop  0s     kube-iptables-tailer  Packet dropped when receiving traffic from netperf-client-a781f2920440 (10.0.2.16)`

Получилось!

2020-11-23 15:37 UTC, Jasstkn approved these changes
Здорово, что добили домашку - аппрув 👍

2020-11-23 15:37 UTC, merged